language: node_js

node_js:
  - "24"

branches:
  only:
    - develop
    - main
    - master

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm ci

script:
  - npm run build
  - docker build . -t=angular-best-doc-web:travis-build-$TRAVIS_BUILD_NUMBER
