services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-best-doc-web
    env_file:
      - .env
    ports:
      - "81:80"
    user: "10001:10001"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
