apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-best-doc-web-configmap
data:
  CI: "true"
  NG_CLI_ANALYTICS: "false"
  PORT: "80"
  NODE_ENV: "local"
  ENABLE_CONSOLE_LOG: "true"
  LOG_LEVEL: "debug"
  BASE_PATH: "/"
