name: Mirror to GitLab 🦊

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure SSH 🔑
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/gitlab_mirror_key
          chmod 600 ~/.ssh/gitlab_mirror_key
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push mirror to GitLab 🪞 🦊
        run: |
          git remote add gitlab git@gitlab.com:caprilespe/angular-best-doc-web.git
          GIT_SSH_COMMAND="ssh -i ~/.ssh/gitlab_mirror_key -o StrictHostKeyChecking=yes" git push --mirror gitlab
